### ISSUE TITLE
Working holiday doing OpenMoji

### ISSUE THREAD

**Issue by lizbravob** [hfg-gmuend/openmoji#134]
I worked in two versions for different Openmoji
#flatbread #piñata #tamale #blueberries #longdrum

![blueberries 2](https://user-images.githubusercontent.com/60933333/75769772-7c5f1280-5d25-11ea-8804-2b5e5f7c4336.jpg)
![blueberries](https://user-images.githubusercontent.com/60933333/75769775-7ec16c80-5d25-11ea-83e1-81e6d494a9c6.jpg)
![flatbread 2](https://user-images.githubusercontent.com/60933333/75769779-7f5a0300-5d25-11ea-92cd-76050fa265b6.jpg)
![flatbread](https://user-images.githubusercontent.com/60933333/75769780-808b3000-5d25-11ea-84e8-a2b0071244ee.jpg)
![longdrum 2](https://user-images.githubusercontent.com/60933333/75769783-808b3000-5d25-11ea-8f5a-44649f54c4f2.jpg)
![longdrum](https://user-images.githubusercontent.com/60933333/75769786-8123c680-5d25-11ea-9593-14f10a830053.jpg)
![piñata 2](https://user-images.githubusercontent.com/60933333/75769789-8123c680-5d25-11ea-8ced-aceb0b022c2d.jpg)
![piñata](https://user-images.githubusercontent.com/60933333/75769790-81bc5d00-5d25-11ea-96e1-60cbec22fd0e.jpg)
![tamale 2](https://user-images.githubusercontent.com/60933333/75769791-81bc5d00-5d25-11ea-81bf-26ca60edea07.jpg)
![tamale](https://user-images.githubusercontent.com/60933333/75769792-8254f380-5d25-11ea-9cf2-ff2999bbf93d.jpg)

I can't seem to upload svgs as-is to Github.
[Openmoji.zip](https://github.com/hfg-gmuend/openmoji/files/4280863/Openmoji.zip)
[Openmoji_v2.zip](https://github.com/hfg-gmuend/openmoji/files/4280866/Openmoji_v2.zip)

**Comment by carlinmack** [comment]
all very good! are you familiar with `git` at all? if not we can try figure something out @b-g

**Comment by lizbravob** [comment]
Thanks. I've never worked with Git

**Comment by carlinmack** [comment]
You can upload the files through the web interface!

![image](https://user-images.githubusercontent.com/6676843/75793876-fc917200-5d3d-11ea-9aeb-2c1481124d41.png) 

https://github.com/hfg-gmuend/openmoji/tree/lizbravob/src/food-drink/food-fruit
- blueberries: 1FAD0.svg

https://github.com/hfg-gmuend/openmoji/tree/lizbravob/src/food-drink/food-prepared
- tamale: 1FAD4.svg
- flatbread: 1FAD3.svg

https://github.com/hfg-gmuend/openmoji/tree/lizbravob/src/activities/game
- pinata: 1FA85.svg

https://github.com/hfg-gmuend/openmoji/tree/lizbravob/src/objects/musical-instrument
- longdrum: 1FA98.svg

**Comment by carlinmack** [comment]
To comment on the colours I would say:
- blue version of blueberry
- yellow version of flatbread
- red version of drum
- first version of pinata, maybe without the 'spikes' on the legs?
- yellow version of tamale

**Comment by lizbravob** [comment]
cool, thank you for the support! :)

**Comment by lizbravob** [comment]
I can't upload the SVGs
<img width="1036" alt="Captura de Pantalla 2020-03-03 a la(s) 15 38 53" src="https://user-images.githubusercontent.com/60933333/75808006-26aa5a80-5d65-11ea-9cbb-8fbf56a511c1.png">

**Comment by carlinmack** [comment]
oh no! let me see if I can fix that

**Comment by carlinmack** [comment]
I don't have permissions to change any settings, @b-g can you help us?

**Comment by b-g** [comment]
@carlinmack No unfortunately this won't work due to push access restrictions. I'm sorry! We should really tinker a better workflow. Lets continue the conversation on that at #135.

@lizbravob Many thanks for the super contributions! Sorry that Github is so complicated and the current workflow so unwelcoming!

Basically I just see two options:
1. We upload the files to Github (no problem, happy to do that)
2. You see it as a geeky challenge to learn how to do your first PR with Github. There is a nice and friendly tutorial by Daniel Shiffman (The Coding Train): https://www.youtube.com/watch?v=_NrSWLQsDL4

Either way is fine for us. Please decide on your own :)

Many thanks again!

PS. If you want to be featured under team https://openmoji.org/about/#team we would also need a portrait and your links.

**Comment by lizbravob** [comment]
Yes, of course. Upload it. This file has the final version.
[Openmoji_lizbravo.zip](https://github.com/hfg-gmuend/openmoji/files/4287260/Openmoji_lizbravo.zip)
If I have more time I'll like to continue collaborating. :)

Yes, I want to.
IG: https://www.instagram.com/lizbravob/
TW: https://twitter.com/lizbravob

Do you need a photo or my version in openmoji?

Thanks for the support!

**Comment by b-g** [comment]
@lizbravob Many thanks looks good! Will add your OpenMojis in the next days ... so that we can include them in the next release :)

Would be super to see more of you here!

> Do you need a photo or my version in openmoji?

We need a vector style portrait of you. If you want. This is not a must. This is just a way to give nicer credits than mentioning you in the changelog.txt file.

Here is an example how I look 👀 


<img width="161" alt="Screen Shot 2020-03-04 at 15 15 55" src="https://user-images.githubusercontent.com/480224/75888066-1197ff00-5e2b-11ea-8278-3af6e6704e2b.png">

**Comment by b-g** [comment]
@lizbravob Wow that was quick! :) Please attach it as zipped svg. We will handle the rest. Many thanks!!

**Comment by lizbravob** [comment]
Thanks!! :)
[lizbravob.zip](https://github.com/hfg-gmuend/openmoji/files/4288076/lizbravob.zip)

**Comment by carlinmack** [comment]
closed with 60a5cb79, will keep open for headshot etc

**Comment by b-g** [comment]
Done with https://github.com/hfg-gmuend/openmoji-website/commit/a4430dd9bb59000b9bc37e03f70c07a82bf0ccff. Added you @lizbravob to the team! Welcome! :) Will be online with next deployment of the website. Give it a week. Thanks
