### ISSUE TITLE
Standardise "prohibited" signs

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#164]
![image](https://user-images.githubusercontent.com/6676843/78454376-c1989c00-7665-11ea-9761-9566d5fbe50a.png)
I was going to do the no hand shake sign but realised that we don't have consensus on the best way, thoughts? I think the "no bicycles" one is best

**Comment by b-g** [comment]
Hi @carlinmack, 

Yes making them consistent would be great! I agree in the grid above the no bicycles is nice ... however I think it is better to go with the shape of e.g. no littering, because this prohibited sign gives the designer more "space" to display the prohibited things inside. I would recommend to go:

- red of no bicycles
- shape of no littering

What do you think? cc @dnlutz

**Comment by carlinmack** [comment]
Couple questions:

- Which colour of red do you prefer, No-Bicycles or No-Littering? 
- No-Bicycles is at a 45° angle whereas No-Littering is at a slightly more acute angle, does it matter, and is one better?
- should Prohibited stay the same as there is nothing in the middle or should it be consistent with the others?

**Comment by b-g** [comment]
Sure! I would suggest:

- bright red of No-Bicycles 
- 45°
- smaller line of No-Littering in terms of shape
- "Prohibited" consistent with the new standard

But please veto if you don't like it.

**Comment by carlinmack** [comment]
👍👍 will do this tomorrow as I'm busy today for once
