### ISSUE TITLE
New design for exploding head (1F92F)

### ISSUE THREAD

**Issue by taralynnconnelly** [hfg-gmuend/openmoji#172]
Hello! I saw a request to update 1F92F on #143 and wanted to share my contribution.

![1F92F-grid](https://user-images.githubusercontent.com/11408204/79163492-3168fe00-7dad-11ea-9c27-d282c8cc4f5b.png)
http://taralynnconnelly.com/1F92F.svg

The facial expression is based on 1F62F.
![1F62F](https://user-images.githubusercontent.com/11408204/79162810-e5698980-7dab-11ea-8127-938f5f9f8fa0.png)

Looking forward to hearing your feedback!

**Comment by carlinmack** [comment]
Great job! Could you add the back of the head with the darker yellow (f1b31c) fill? Thanks!

**Comment by taralynnconnelly** [comment]
@carlinmack Thank you! I had fun with it. Here's how it looks with the back of the head included.

![1F92F-grid](https://user-images.githubusercontent.com/11408204/79167025-75abcc80-7db4-11ea-8239-a70c087a1e20.png)
http://taralynnconnelly.com/1F92F.svg

**Comment by carlinmack** [comment]
great! I'll add it now :)

**Comment by carlinmack** [comment]
Done!

**Comment by taralynnconnelly** [comment]
awesome! i will contribute some more soon. 🙂

**Comment by carlinmack** [comment]
PS if you could upload the version with the grid next time, that'd be easier for me!

**Comment by b-g** [comment]
@taralynnconnelly 🤯! :) Many thanks!!

**Comment by b-g** [comment]
Hi @taralynnconnelly! @carlinmack just added your 🤯 to OpenMoji. Will be shipped with the next release ...

One more thing: We ask everyone who contributed an OpenMoji to submit a self portrait (and potential social media links), so that we can feature you at https://openmoji.org/about/#team = the hall of fame :) This is not a must ... rather a lovely tradition most contributors followed. If so, you can either post the portrait/infos here or if you are into Github directly a PR at https://github.com/hfg-gmuend/openmoji-website. Many thanks for considering! 🙏

**Comment by taralynnconnelly** [comment]
@b-g Just created a pull request for my avatar and bio! I'm still pretty new to GitHub so let me know if there's anything I should do differently for future PRs. #106

**Comment by b-g** [comment]
@taralynnconnelly Brilliant! Call yourself a Github pro now! :) Merged! Will be online with the next deployment of the website (give it a few days). Thanks!!

**Comment by b-g** [comment]
Preview is here: https://hfg-gmuend.github.io/openmoji-website/ (our staging instance)
