### ISSUE TITLE
How to cite the OpenMoji project in a paper?

### ISSUE THREAD

**Issue by Vrroom** [hfg-gmuend/openmoji#294]
Thanks for curating this dataset! 

I was wondering whether there was a bibtex that I can copy-paste for citing this dataset in my paper.

So far, I have come up with: 

```
@misc{openMoji
  title = "OpenMoji",
  year = "2020", 
  howpublished="https://github.com/hfg-gmuend/openmoji"
}
```

**Comment by b-g** [comment]
That is a good question :) No we don't have that.

But I would not refer to OpenMoji as a dataset, I would rather call an open source emoji or maybe pictorgram set. 

Maybe something like this? No really familiar with bibtex, please tweak and discuss here quickly ... so that we can add it to the repo. Cheers.

```
@misc{OpenMoji
 title = "OpenMoji – Open source emojis for designers, developers and everyone else!",
 author    = "Benedikt {Groß}, Daniel {Utz}, Carlin {MacKenzie} and everyone openmoji.org/about/#team",
 institution = "Hochschule für Gestaltung Schwäbisch Gmünd",
 year      =  2018,
 address   = "Schwäbisch Gmünd",
 edition   = "v13.0"
 howpublished="https://github.com/hfg-gmuend/openmoji"
}
```

**Comment by Vrroom** [comment]
Really appreciate your response! Yes, what you have suggested works. This is what I'll be adding in my draft. 

Thanks!
