### ISSUE TITLE
Hourglass Emoji Bug

### ISSUE THREAD

**Issue by ccoenen** [hfg-gmuend/openmoji#3]
Not sure if this is the right place, but: the hourglass emoji are weird. If these were actual hour glasses, the sand would collect at the bottom. In these two, it collects at the center :-D

http://openmoji.org/library.html?group=travel-places&emoji=231B
http://openmoji.org/library.html?group=travel-places&emoji=23F3

**Comment by b-g** [comment]
@ccoenen Thanks for spotting and reporting! Yes you are right our hourglass emojis seem not to obey the laws of gravity, sorry for that! :) We will try to fix this in the next iteration.

cc @dnlutz

**Comment by ccoenen** [comment]
No need to be sorry :-D there are literally hundreds of emoji, ther's probably a few more bugs hidden ;-)

**Comment by b-g** [comment]
Fixed with https://github.com/hfg-gmuend/openmoji/commit/8f99f07b5edbd326415c67465ddca3590923c466!

🙏 @dnlutz 

![screen shot 2018-05-16 at 14 32 22](https://user-images.githubusercontent.com/480224/40117464-5863a7ce-5917-11e8-97af-c721536757ae.png)
![screen shot 2018-05-16 at 14 32 39](https://user-images.githubusercontent.com/480224/40117465-587d5110-5917-11e8-8453-5acf0c309651.png)
