### ISSUE TITLE
Release date for OpenMoji 13.1?

### ISSUE THREAD

**Issue by woswos** [hfg-gmuend/openmoji#326]
Hi everyone!

What is the planned release date for OpenMoji 13.1?

**Comment by b-g** [comment]
Hi @woswos, yes ... we are a bit behind. OpenMoji v13.1 is planned for the very beginning of Juli. We first wanted to add some multi-skintone features to /library of OpenMoji.org (the website), so that people could find and browse those emojis. Which happened over the last weeks, so we don't have any longer an excuse to sit on a new release. Stay tuned!
