### ISSUE TITLE
cannot download repo via github

### ISSUE THREAD

**Issue by andest01** [hfg-gmuend/openmoji#51]
# Could not download this repo via github

OS: Windows 10
```
λ git --version
git version 2.16.2.windows.1
```

```
$ git clone git@github.com:hfg-gmuend/openmoji.git
Cloning into 'openmoji'...
Enter passphrase for key 'C:\Users\swe/.ssh/id_rsa':
remote: Enumerating objects: 110, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (78/78), done.
fatal: The remote end hung up unexpectedly6 GiB | 6.39 MiB/s   s
fatal: early EOF
fatal: index-pack failed
```

![image](https://user-images.githubusercontent.com/1424223/67147635-226d1d00-f25c-11e9-85dd-a53f9fa00909.png)

This is more of a heads up than anything else.

**Comment by b-g** [comment]
Hi @andest01, many thanks for the heads up! Yes the OpenMoji repo became really big, due to working with the horrible .ai files at the beginning. We still have to deal with this bad legacy in terms of file size footprint. However if you have a fast internet connection I can confirm that it works as expected. Also you can clone a repo without the entire history, note the `--dept` flag e.g.

```
git clone --dept 1 https://github.com/hfg-gmuend/openmoji.git

Cloning into 'openmoji'...
remote: Enumerating objects: 16238, done.
remote: Counting objects: 100% (16238/16238), done.
remote: Compressing objects: 100% (13123/13123), done.
remote: Total 16238 (delta 4688), reused 13289 (delta 3107), pack-reused 0
Receiving objects: 100% (16238/16238), 57.08 MiB | 4.21 MiB/s, done.
Resolving deltas: 100% (4688/4688), done.
Checking out files: 100% (21032/21032), done.
```
