### ISSUE TITLE
HTML Demo not working

### ISSUE THREAD

**Issue by AstroGD** [hfg-gmuend/openmoji#53]
Im trying to insert openMoji as a font to my html page but it only displays the black-font style.
I downloaded your Demo and opened it and it also does only display black font with both fonts, the color and the black one. To be clear: This is your demo and I did not change anything in the code.
It seems like the downloads on your website both download the black font type.

![openMojiError](https://user-images.githubusercontent.com/35271072/67159046-ca0f4b80-f33f-11e9-93fe-fac1604d028d.png)

**Comment by dnlutz** [comment]
Unfortunately I get the same result. I'm pretty sure the font actually contains the correct color SVGs but it is rendered as black and white in the browser. Sadly we do not have any satisfactory solution for the OpenMoji fonts at the moment.

The first font versions were made with the Illustrator plugin Fontself Maker: https://www.fontself.com/ 
But our project turned out to be too extensive for the software.

The current font versions are made with the help of scfbuild: https://github.com/13rac1/scfbuild 
But it does not work out well for our SVGs (I suppose at the moment our fonts are more "alpha" than "beta" ; )

At the moment we don't know which other tools we could use to generate working fonts. Are there any hints or recommendations from experienced (color) font producers?

**Comment by AstroGD** [comment]
Ah I see, thanks for the info.
Maybe it would be a good idea to make an FAQ or a warning / information - message on the website so that people using openmoji now what causes this issue and dont need to open an issue on github every time.

**Comment by felixhaeberle** [comment]
Doesn't seem like there is good progress for support in Chromium, see this conversation: [Issue 306078: SVG in OpenType support](https://bugs.chromium.org/p/chromium/issues/detail?id=306078).
