### ISSUE TITLE
Improve/fix OpenMoji Colorfont (and Black)

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji#93]
**The OpenMoji colorfont is currently just a proof of concept and only works in Firefox.** 

We hope to improve this to proper colorfont in the near future (or at least in the long run). Sorry + stay tuned and follow this thread for updates!

**Comment by b-g** [comment]
https://github.com/hfg-gmuend/openmoji/issues/66#issuecomment-547885696

**Comment by b-g** [comment]
This is to gather a few links.

Currently we use https://github.com/hfg-gmuend/openmoji/blob/master/font/README.md basically [SVGinOT Color Font Builder ](https://github.com/13rac1/scfbuild)a 3-4 year old and stale project. The resulting Colorfont seem just partly to support the standard. They just work in Firefox :(

Other links:
- The [google noto-emoji repo](https://github.com/googlefonts/noto-emoji) seems to have the tooling to generate PNG based colorfonts
- https://colorfonts.langustefonts.com/howto.html (lot's of good links, but resulting font is also just Firefox)

**Comment by bohnacker** [comment]
To simplify the discussion: 
Which format should we support? Right now, there are four:
PNG based: Google's CBDT/CBLC tables and Apple's SBIX table
Vector based: Microsoft's overlapped glyphs (COLR/CPAL tables) and Mozilla and Adobe’s SVG (SVG table)

These formats are supported as follows at the time (source: https://pixelambacht.nl/2014/multicolor-fonts/):
<img width="830" alt="Bildschirmfoto 2019-12-03 um 19 30 53" src="https://user-images.githubusercontent.com/2828139/70079230-9e50d800-1604-11ea-843c-20e66e936bfe.png">
<img width="836" alt="Bildschirmfoto 2019-12-03 um 19 30 43" src="https://user-images.githubusercontent.com/2828139/70079246-a3ae2280-1604-11ea-86e2-9d462c7981c6.png">

Checking with https://pixelambacht.nl/chromacheck/ there also seems to be supported SBIX in Chrome.

My opinion: there's no way around SVG because it's much more powerful than COLR. I guess, sooner or later all browsers will support SVG Color Fonts. 

Our situation:
<img width="1824" alt="Bildschirmfoto 2019-12-03 um 19 23 40" src="https://user-images.githubusercontent.com/2828139/70080063-2e435180-1606-11ea-98dd-fc5dd5705e6d.png">
From left to right: Chrome, Firefox, Safari (I'm on Mac, so no quick check for Edge, ...)

Safari should support SVG Color Fonts. So, that's a bug.

**Comment by b-g** [comment]
Hi @bohnacker, many thanks for putting this together. I'm agnostic and happy to support a single standard e.g. SVG properly ... just it should be 100%. Currently our colorfont is just rendered in Firefox, but should also usable in Safari, Adobe CC, Sketch, Affinity ... which is not the case. Also @dnlutz is strongly in favor of SVG ... Hence I think SVG is the best bet, however I couldn't find a good tooling for it back at the beginning of 2019. Also note: Google Noto Emoji tooling is PNG based.

**Comment by AndydeCleyre** [comment]
I don't know what joypixels (emojione) is doing, but their color font seems to display nicely in browsers and qt apps (including konsole) on Arch linux with the repo package, which fetches [joypixels-android.ttf](https://cdn.joypixels.com/arch-linux/font/5.0.3/joypixels-android.ttf).

**Comment by danielleontiev** [comment]
The b/w font looks damaged as well for me in LaTeX:
![uwSWqRS](https://user-images.githubusercontent.com/24596613/70354452-97ce9480-1880-11ea-9390-b049ad91da0c.png)

**Comment by b-g** [comment]
Hi @bohnacker, https://www.glyphrstudio.com/online/ a free online font editor might be interesting in terms of debugging the black font. (But also no colorfont support currently https://github.com/glyphr-studio/Glyphr-Studio-1/issues/270)

**Comment by b-g** [comment]
Related font issue from #96:

> Not sure how valid this is but using the black openmoji font and vscode, it shows ones we support as a single character and others as multiple characters

> However we do have a pirate flag emoji so maybe this is also an issue with the font that we haven't realised?

![image](https://user-images.githubusercontent.com/6676843/70368879-7c628a00-187e-11ea-9fd2-09b67a9cc82d.png)

**Comment by bohnacker** [comment]
I checked a few things with our color and black fonts and compared it with the fonts "EmojiOne Color" and "Twitter Color Emoji". I chose those because they are not from a vendor of operating systems (Apple, Windows, Google). EmojiOne is an Opentype font while the one from Twitter is Truetype. Ours is Truetype too.

It appears that our fonts are not that bad in general, but there are quite some things to improve.

The following screenshot is made in InDesign on Mac and it seems to handle the Openmoji Color font perfectly. Openmoji Black has some problems. The conversion from SVG to Truetype glyphs ignores stroke-linecap="round" and stroke-linejoin="round" (most obvious on the smiley and the TM-sign). Also, overlapping paths are not converted well (hand, soccer ball, santa claus).
<img width="617" alt="Screenshot InDesign Mac" src="https://user-images.githubusercontent.com/2828139/71724232-d62f8300-2e2f-11ea-9690-f53e148d7afd.png">

For the black font I see two possible solutions:
1. Remove all strokes from all our source emojis and convert it to filled areas.
2. Find a better conversion algorithm.
The first solution is not very practical and desirable. I think it's good to have line elements in the source files as much as possible. Otherwise improving the source emojis will be a hassle.

I found another problem with our fonts in InDesign. Ligatures sometimes are split into parts when text gets wrapped. It happend with the hand and the horse but not with the dark santa claus and the flags. I'll try to find out why.
<img width="671" alt="Screenshot InDesign wrapping" src="https://user-images.githubusercontent.com/2828139/71725344-cfa30a80-2e33-11ea-8468-d2912a39c2d9.png">

---

Comparision of the behaviour in browsers:

Firefox (Mac and Windows):
Some problems with our color font shows up. Some strokes are not scaled correctly. I'm mot complete sure why. Maybe it's because there are elements on the color layer that have both a fill color and a stroke color. Or it has something to do with transforms that are still in some emojis.
<img width="1118" alt="Screenshot Firefox Mac" src="https://user-images.githubusercontent.com/2828139/71725120-25c37e00-2e33-11ea-88b5-28fbf2610cc4.png">

Safari (Mac):
Only EmojiOne works (maybe because it's Opentype):
<img width="1116" alt="Screenshot Safari Mac" src="https://user-images.githubusercontent.com/2828139/71725171-455aa680-2e33-11ea-819a-5faad7940ab2.png">

Edge (Windows):
Handles our color emojis perfectly.
![Screenshot Edge Windows](https://user-images.githubusercontent.com/2828139/71725581-d2eac600-2e34-11ea-9a1d-d722f14dcb72.png)

**Comment by bohnacker** [comment]
Maybe we could use some other libraries like this to convert all strokes in the black SVGs to areas before creating the truetype glyphs: 
https://www.npmjs.com/package/js-clipper

It seems to support all we need (stroke-linecap="round" and stroke-linejoin="round"). The fact that it is not developed further on is not a problem in my opinion because it has no dependencies.

Or has anybody good experiences with other libraries for path operations?

**Comment by b-g** [comment]
Hi @bohnacker! A belated happy new year + many thanks for the investigation! That sounds a lot more promising than I've anticipated! Yay! A few comments/thoughts:

OpenMoji Black
- I would vote to introduce a dedicated build process which converts all problematic strokes to shapes ... but not to alter the src svg files
- Instead of js-clipper I would rather bet on paper.js ([in node.js](https://github.com/paperjs/paper.js#installing-paperjs-using-npm)) with the [paperjs-offset](https://github.com/luz-alphacode/paperjs-offset) plugin. (See also the discussion on [Parametrized stroke outlining / expanding / offsetting](https://github.com/paperjs/paper.js/issues/371) with paper.js) 
- Q: Would we have to convert every stroke or just the ones with stroke-linecap="round" and stroke-linejoin="round" attributes?

OpenMoji Color
- Q: Is the issue with svgs which have both a fill color and a stroke color a Firefox bug only? If so ... should we simply ignore it?
- Q: Should we ditch current color font generator or stick with it? I can offer to improve the generator "scfbuild" to support properly generating the two fonts without the current hustle ... but this makes only sense if the scfbuild is worth the invest. (I guess it won't be possible to generate a colorfont in opentype flavor with scfbuild, or?)

**Comment by bohnacker** [comment]
Hi @b-g, some answers to your questions and suggestions:

> I would vote to introduce a dedicated build process which converts all problematic strokes to shapes ... but not to alter the src svg files

Yes, I think so too. That's the only approach that makes sense.
 
> Instead of js-clipper I would rather bet on paper.js ([in node.js](https://github.com/paperjs/paper.js#installing-paperjs-using-npm)) with the [paperjs-offset](https://github.com/luz-alphacode/paperjs-offset) plugin. (See also the discussion on [Parametrized stroke outlining / expanding / offsetting](https://github.com/paperjs/paper.js/issues/371) with paper.js)

I also agree. I had a look at js-clipper and found that it converts all curves to polygons. The result will be glyphs that will look bad when scaling them up a lot. Still we have to check if paperjs is doing everything correctly.

> Would we have to convert every stroke or just the ones with stroke-linecap="round" and stroke-linejoin="round" attributes?

Best would be to convert every stroke beforehand because scfbuild (or whereever this is done) has also problems with paths that are crossing itself (see hand and soccer ball in the above examples). In the end (as a glyph) everything will be areas.

> Q: Is the issue with svgs which have both a fill color and a stroke color a Firefox bug only? If so ... should we simply ignore it?

As far as I've seen, it's a Firefox only bug. Maybe we could ignore it and hope for a bug fix on the Firefox side.

> Q: Should we ditch current color font generator or stick with it? I can offer to improve the generator "scfbuild" to support properly generating the two fonts without the current hustle ... but this makes only sense if the scfbuild is worth the invest. (I guess it won't be possible to generate a colorfont in opentype flavor with scfbuild, or?)

I think we could stick with scfbuild. In general it is doing a good job as far as I've seen. I don't know if it is possible to switch to opentype using scfbuild. I think the truetype glyph creation is done with the fontforge library which should also be capable of generating opentype glyphs. But there might still be a lot more things to change...

**Comment by mikemaccana** [comment]
**Note this image is 5 years out of date (it's from 2014)**:

<img width="830" alt="70079230-9e50d800-1604-11ea-843c-20e66e936bfe" src="https://user-images.githubusercontent.com/172594/71816003-277e8300-3079-11ea-85c7-cf31a5ce73fd.png">

COLR works fine in Chrome now

https://pixelambacht.nl/chromacheck/

**Comment by b-g** [comment]
@mikemaccana Thanks for the heads up!

@bohnacker Many thanks + agree! Should I go ahead and improve scfbuild with a dedicated --black-only flag so that we can streamline the font build process, or is this too earlier and currently not helpful?

**Comment by mikemaccana** [comment]
PS is there a webpage we can see openmoji rendered in COLR format, as a webfont?

**Comment by bohnacker** [comment]
@b-g: If you want you can streamline the font building but it's not urgent from my side. I'll start testing paperjs stroke conversion and exploring the other bugs.

@mikemaccana: We haven't build the font in COLR format (and I'm quite sure that we can't do that in the near future). We concentrate on debugging the SVG color font.

**Comment by b-g** [comment]
via @carlinmack 

The OpenMoji colour font kinda works! You can easily test this by 
- install the OpenMoji colorfont
- go to https://unicode.org/Public/emoji/13.0/emoji-test.txt on (Firefox developer edition)

![image](https://user-images.githubusercontent.com/480224/78555960-6229c000-780e-11ea-8e77-52d35846823e.png)

Note that Pinata is rendered in OpenMoji now. Yay!

@dnlutz 
But it also shows that the size of the glyphs is way too small! We should tweak the size in https://github.com/hfg-gmuend/openmoji/blob/master/font/scfbuild-color.yml#L8. What size would you suggest?

**Comment by dnlutz** [comment]
I would suggest to scale the OpenMoji by factor 1.3
The Y-position is perfect in relation to the baseline.
<img width="930" alt="color_font_scaling" src="https://user-images.githubusercontent.com/38292227/80213627-bff53f00-8639-11ea-8cb8-b2d7c42da465.png">

**Comment by carlinmack** [comment]
Looks good! 

We should highlight where the baseline is in openmoji-template.svg

**Comment by b-g** [comment]
Done. Scaled up by 1.3.

**Scale 1 / Scale 1**
<img width="618" alt="Screenshot 2020-05-05 at 08 20 18" src="https://user-images.githubusercontent.com/480224/81041439-25ed8c00-8eae-11ea-973b-308c143c01af.png">

**Scale 1.3 / Scale 1**
<img width="754" alt="Screenshot 2020-05-05 at 08 35 22" src="https://user-images.githubusercontent.com/480224/81041442-27b74f80-8eae-11ea-99d0-ecbe7c3f752f.png">

**Scale 1.3 / Scale 1.3**
<img width="1140" alt="Screenshot 2020-05-05 at 08 54 33" src="https://user-images.githubusercontent.com/480224/81041446-28e87c80-8eae-11ea-96cb-9c8c8147f962.png">

cc @dnlutz

**Comment by dnlutz** [comment]
Tip top / thank you! These emoji sizes now work much better within "normal" text fonts.

**Comment by carlinmack** [comment]
> Ligatures sometimes are split into parts when text gets wrapped. It happend with the hand and the horse but not with the dark santa claus and the flags. I'll try to find out why.

@bohnacker the people at GitLab also noticed this! https://about.gitlab.com/blog/2018/05/30/journey-in-native-unicode-emoji/

**Comment by carlinmack** [comment]
@mikemaccana you can view how the the emojis look as a font on this website https://hfg-gmuend.github.io/openmoji/ by selecting OpenMoji in the bottom left. There are some bugs but it's pretty good

**Comment by mavit** [comment]
I see that Google have started work on a new tool, [nanoemoji](https://github.com/googlefonts/nanoemoji), to build colour fonts in a variety of formats.  Not all formats are currently implemented, and it doesn't seem to be production quality yet, but I think it's worth keeping an eye on.

**Comment by b-g** [comment]
Thanks @mavit! This is a good pointer! Would you have time to give it spin? ;) Our color font generator seems not the best bet in the long run ... We are keen to have better and more fonts to render OpenMojis on more platforms.

**Comment by mavit** [comment]
Status update for nanoemoji.  It worked for building COLR TTFs when I first tried it, but by the time I got around to containerising the build it had broken because of googlefonts/picosvg#65.

**Comment by b-g** [comment]
Hi @mavit! Many thanks for keeping us posted! Building color fonts via nanoemoji would be mega! Fingers crossed that the bug is soon resolved!

**Comment by Voultapher** [comment]
googlefonts/picosvg#65 has been closed. Just played around with nanoemoji 0.4.1 and openmoji 13.0 and got it to work in chrome and firefox:

linux chromium openmoji-color-cff2_colr_0.otf:

![cff2_colr_0-chrome](https://user-images.githubusercontent.com/6864584/100517099-a9dbce00-3188-11eb-8ec6-26b4b44954a4.png)

While nanoemoji can generate colr v1 fonts these don't seem to be supported by browsers yet.

Here are the fonts I generated if you want to avoid having to build them yourselves:

[openmoji-nanoemoji.zip](https://github.com/hfg-gmuend/openmoji/files/5610682/openmoji-nanoemoji.zip)

**Comment by mavit** [comment]
> While nanoemoji can generate colr v1 fonts these don't seem to be supported by browsers yet.

It depends on your OS.  They mostly work fine on Linux, but not on MacOS.  I don't think we've heard either way about Windows, yet.

**Comment by FoundOne** [comment]
I'm testing the new font form the zip file above. I really like the simplicity of the design of openmoji and I'm glad that I can use it form applications which just use freetype2, but this rendered font is incredibly small, compared to the other emoji fonts. I can barely see what's depicted in a normal text (12-14pt) on my 1080p display of my laptop. The font looks really great when I set it to be more than 20pt.

**Comment by mavit** [comment]
> I'm testing the new font form the zip file above
> ...
> but this rendered font is incredibly small

See #260.

**Comment by MelihDarcanxyz** [comment]
> via @carlinmack
> 
> The OpenMoji colour font kinda works! You can easily test this by
> 
> * install the OpenMoji colorfont
> * go to https://unicode.org/Public/emoji/13.0/emoji-test.txt on (Firefox developer edition)

My Firefox browser shows everything with colors but unfortunately I can't get colorful emojis on Brave (Chromium spin-off).

**Comment by shaurya1709** [comment]
I think we should change to compiling fonts with nanoemoji.
There is an older version by @Voultapher that loads the colourful emojis in Brave. And it is not as buggy as the current version

**Comment by carlinmack** [comment]
see #260 for the saga of using nanoemoji instead :)

**Comment by Kxeo** [comment]
My solution to the OpenMoji font not working anywhere else other than firefox?
Make a extension that replaces emojis with OpenMojis.
Kinda like those extensions that replace emojis with Twemojis

**Comment by RobertWinslow** [comment]
Here's an oddity I found. The line height of the font is too high when viewed in some browsers, namely Chrome or Safari on MacOS. 
See this example screenshot:
![openmoji-lineheight](https://user-images.githubusercontent.com/5784659/153933384-96604c8b-bd53-452c-9ad0-6c2397b1fa8b.png)

This is caused by certain glyphs having elements placed far outside where they should be. The commonality between the broken glyphs is that in their SVG source, they have an element which is rotated around a point other than the origin. When certain browsers display these glyphs, they rotate those pieces around (0,0) instead of the point they are supposed to rotate them around. If the transform attribute is set using a matrix or a rotation about the origin, these browsers display the resulting glyphs fine.

I found that when using FontForge to build a vanilla ttf version of the font, the same glyphs were misrendered in the same way. So I suspect the ultimate source of the error lies in FontForge's SVG importation function.

**Comment by RobertWinslow** [comment]
I am working on an implementation of the black font using FontForge's import tools.

I'd like some feedback on a couple minor implementation details:

- All of the regional flags look the same in outline form. They are each just a blank rectangle. **Would it would be sensible to exclude regional flag characters from the black ttf?** 
    - Simply excluding the characters would lead to a fallback glyph being used: likely some other emoji font, and worse case a blank square. This would be at least as informative to the user, and seems like the best option to me.
    - If Regional Indicator Symbol Letters were added to OpenMoji, as discussed in issue [351](https://github.com/hfg-gmuend/openmoji/issues/351), then excluding regional flags from the font would result in the flags being rendered as a pair of letter glyphs. This would of course require extra work.
    - A third option, which would require *substantially* more work, is to include in each flag's source a "line-supplement" group which contains the region's indicator characters. This is similar to what some other color emoji fonts use as a monochrome fallback: ![screenshot of Microsoft's emoji font displaying flag fallbacks in Google Chrome](https://user-images.githubusercontent.com/5784659/157326717-8e7ece0e-783e-419f-b99c-482403ec115b.png)

- There are some characters which are present in Unicode in both emoji and non-emoji forms, distinguished by a variation selector FE0F. **Should both codepoints be encoded into the font?** 
    - EG: "👁" has codepoint 1F441, while "👁️" has codepoint 1F441-FE0F. OpenMoji's data files only associate the eye emoji with the former codepoint. In many applications, these two codepoints are treated as the same. However, with my font in its current implementation, some applications will render the latter codepoint in the system's default emoji font because 1F441-FE0F isn't *technically* present in OpenMoji.
    - Looking at Unicode's [emoji test file](https://unicode.org/Public/emoji/14.0/emoji-test.txt), it seems there are about 200 such characters.  
    - If both codepoints are used, then I'm not sure where to put the list of such characters; I don't see a relevant data field in OpenMoji's data files. The easiest thing to do would just be to include a array of codepoints in my build script, but that's less future proof.

**Comment by b-g** [comment]
@RobertWinslow Many thanks for the thoughts! Super! Please gives a day to ponder on the questions and to double check once more the quality of the generated glyphs of [OpenMoji-MonoChrome.ttf](https://github.com/RobertWinslow/openmoji/blob/monochrome-font/font/OpenMoji-MonoChrome.ttf). Stay tuned.

**Comment by dnlutz** [comment]
Dear @RobertWinslow thank you for your work on the fonts! The overall curve quality looks really good (as good as it can get with our mixed quality source svgs ; )

However, the fonts are really a tough topic and I have discovered a some issues when checking the files in InDesign:

![duplicates](https://user-images.githubusercontent.com/38292227/157615200-96630965-4653-497e-b0a9-dbe7b86c3302.png)
Duplicates: Some glyphs appear multiple times in an untraceable order.

![fill](https://user-images.githubusercontent.com/38292227/157615366-040da770-2b09-491b-935d-f35d60624751.png)
Fillings: Some characters have areas completely filled with black.

Do you think these issues could be resolved by code? We try to avoid manual interventions during the font built process – the effort can quickly become unmanageable ; )

At the moment the width of the glyph equals the bounding box of the paths, all emoji should get a uniform with.

I hope I have not discouraged you and I don't know if all this is feasible – but the fonts are definitely a tough job (since the start of OpenMoji in 2018).

Many Greetings

Daniel

**Comment by RobertWinslow** [comment]
@dnlutz 

> Duplicates: Some glyphs appear multiple times in an untraceable order.

I suspect this is related to the way I'm handling skin-tone variations. I'm planning to try another way of handling those, though I have no clue whether it will resolve this particular issue. Alternatively, the issue might lay in how TrueType handles ligatures. OpenType handles ligatures more gracefully, so switching from ttf to otf might resolve it.

I had considered leaving skin-tone variants out of the font (it's a monochrome font, after all), but this would cause problems for glyphs with mixed skin tones, as the skin-tone codepoint occurs in the middle of the ligature.

> Fillings: Some characters have areas completely filled with black. Do you think these issues could be resolved by code?

Unfortunately, I'm not sure whether they can be.  There used to be very many more of these errors, and I was able to resolve most of them by cleaning up the source files. That was the impetus behind [this pull request](https://github.com/hfg-gmuend/openmoji/pull/375). A lot of the remaining fill errors are bespoke to individual glyphs rather than systemic issues.

 For example, I've spent a while looking at the leg of that orangutan: 🦧. The issue there is that the path for the leg loops back around and self-intersects without actually being closed with a `z` command. This causes FontForge to 'helpfully' interpret it as a solid shape before the expandStroke method has a chance to be called. 

![image](https://user-images.githubusercontent.com/5784659/157800554-321a1f49-272a-4a00-b808-cf540b90f47b.png)

A very very similar, but not quite identical, problem plagues the handshake 🤝 glyph. And now looking at the gear 
⚙[2699](https://openmoji.org/library/#emoji=2699), its source also has one of these 'pseudo-closed' paths.   

The 🦧 glyph in the font could be corrected by:
- Altering the leg path in some way - Making it properly closed with a `z` command, or 'splitting' the path by inserting an `m 0 0` command in between two other commands.
- Or by using a different build process. What needs to be done for each glyph is: Load up the black svg, convert strokes to paths, merge all paths into a single element, and then import that element's outline as the outline of a glyph. That's exactly what I'm having FontForge do. It's clearly not doing it *exactly* as I'd like it to, but I wasn't able to find another easy-to-use tool to automate the process. And even if another tool were used, it might just introduce it's own new set of rendering errors. 'Better the devil you know' so they say. 

All that said, some of those filled glyphs aren't actually mis-rendering.  I recognize 'keyboard' [E1D1](https://openmoji.org/library/#emoji=E1D1) and ◭ [25ED](https://openmoji.org/library/#emoji=25ED). That's just the 'line-supplement' layer being drawn. 

> At the moment the width of the glyph equals the bounding box of the paths, all emoji should get a uniform with.

Okay. That's an easy change.

> I hope I have not discouraged you and I don't know if all this is feasible – but the fonts are definitely a tough job

Haha, if I were that easily discouraged, I wouldn't have gotten this far along. Thanks for the feedback. Like you say, it's a tough project.

**Comment by RobertWinslow** [comment]
@dnlutz 

Could you take a look at [this new version of the font](https://github.com/RobertWinslow/openmoji/blob/black-font-ff/font/OpenMoji-Black.ttf), to see if the duplicate glyph issue has been resolved?
I changed the method I used to handle the skintone variants. 

Re: Giving the glyphs a uniform width. If the glyphs are scaled up by a factor of 1.3, should the width also be set 30% bigger than normal? If yes, then the font ends up unusually wide. If no, some glyphs are so wide that either they will overflow their bounding box or they will need to be scaled back down a bit. See the eye (👁️  1F441) for an example of a very wide vector source. In [the script I used to generate the font file](https://github.com/RobertWinslow/openmoji/blob/black-font-ff/helpers/build_black_font_with_fontforge.py), I included multiple parameters to adjust the width of glyphs. I'm just not sure what they should be set to.

**Comment by dnlutz** [comment]
dear @RobertWinslow 
there seem to be less duplicates now. but there are still some, for example "People Holding Hands" exists several times. also the fill bugs are still there:
<img width="262" alt="220406 fill" src="https://user-images.githubusercontent.com/38292227/161936988-49c723d4-7a44-4f8a-938a-d6c0daf8d1fc.png">
metrics / scaling: it would be ideal when all the glyphs retained the 72 px bounding box from the source svgs (emoji + bounding box should be scaled in the same ratio). i hope this makes sense. many greetings daniel

**Comment by RobertWinslow** [comment]
Minor update on the above mentioned duplicate-glyph issue. I thought I had fixed skintone variants showing up as duplicate glyphs. But actually, I had just accidentally removed many of the skintone variants. Further testing has fixed the latter issue, but I suspect the issue of "duplicate" glyphs might not be solvable. (They aren't actually duplicates, just identical.)

**Comment by shaurya1709** [comment]
The only color format I know of which is cross-browser compatible is COLR(v0). Chromium(and Chromium-based browsers) do support COLRv1 since chrome 98.

**Comment by dnlutz** [comment]
Is it possible for users to change the colors ind COLRv1?

**Comment by dnlutz** [comment]
Okay … I just spotted this article: https://css-tricks.com/colrv1-and-css-font-palette-web-typography/
Maybe we should go all in with COLRv1 and dump all other font formats?

**Comment by mavit** [comment]
> Maybe we should go all in with COLRv1 and dump all other font formats?

That would certainly simplify things if we can, but I thought [COLR wasn't supported by Adobe Illustrator](https://github.com/hfg-gmuend/openmoji/pull/260#issuecomment-810167952)?  Is that still true, and, if so, is it a showstopper?

**Comment by RobertWinslow** [comment]
@dnlutz

I've made another pass at improving the Black font. I've uploaded two versions of the font:
[TwoVersionsOfOpenMojiBlackFont.zip](https://github.com/hfg-gmuend/openmoji/files/10147148/TwoVersionsOfOpenMojiBlackFont.zip)

This zip contains two files: called `OpenMoji-Black.ttf`  and `OpenMoji-Black_sansSkintoneAndFlags.ttf`. The latter excludes two sets of glyphs:

- skintone variants
- country flags

**Skintone Variants**: In a monochrome font, skintone variants appear identical to the base glyph. In `OpenMoji-Black.ttf`, I implemented the skintone variants as a pointer to their base glyph, as defined in the `skintone_base_hexcode` of openmoji.csv. This reduces file size and ensures proper rendering, but may be the cause of the strange 'duplicates' you identified previously.
![Screen Shot 2022-12-03 at 12 36 36 PM](https://user-images.githubusercontent.com/5784659/205457485-e7732f53-6c5b-414d-b5d5-58f7d55ebbba.png)

**Country Flags**: The country flags, with few exceptions, are depicted as identical black rectangles in the Black version of OpenMoji. With the recent addition of regional indicator letters, a monochrome font might be more useable if the  country flags are excluded. If this is done, then the flags will be rendered as pairs of regional indicator letters
![Screen Shot 2022-12-03 at 12 37 38 PM](https://user-images.githubusercontent.com/5784659/205457477-9e3e2302-8a32-44f2-9a50-0ece16a1f538.png)

I've set up a [build script for the font](https://github.com/RobertWinslow/openmoji/blob/black-font-with-fontforge/helpers/build_black_font_with_fontforge.py) so neither of these exclusions are implemented, but can be toggled on by changing a pair of global variables near the beginning of the file.

**Comment by dnlutz** [comment]
Thank you @RobertWinslow !

The paths look pretty neat now! There are still some black fillings, but i'm pretty sure that it's not the fault of your algorithms but our source svgs ; )

<img width="977" alt="221206 openmoji_font_test_01" src="https://user-images.githubusercontent.com/38292227/205848905-9af4679e-fb98-4a44-b7d3-d10ec1260f93.png">

The two versions have pretty much the same file size. I would go for the Google Noto way: 
– Regional indicators for the flags
– No skintone indication

What do you think?

And could you please include an empy space sign (U+0020)? … and a hyphen would be neat (U+002D ; )

**Comment by RobertWinslow** [comment]
@dnlutz  If a hyphen is added, which of the following styles would be preferred?
![002D](https://user-images.githubusercontent.com/5784659/208782333-df6a6d69-2b39-4194-bd3e-da0ebc36394f.png) ![002D (2)](https://user-images.githubusercontent.com/5784659/208782334-a332c501-b5d3-48e6-ae97-fe9875c58e7a.png)

Or would it be better to duplicate the heavy minus sign?
![2796](https://user-images.githubusercontent.com/5784659/208782787-51d26716-8bbc-426f-af30-f5c7a84eb5e4.png)

**Comment by dnlutz** [comment]
thank you! for the sake of consistency i would vote for the duplicated heavy minus sign.

**Comment by s-light** [comment]
Hello everyone 
What is the current Städte oft the fonts?
